name: 'Sanic Actions'
description: 'GitHub Actions to Manage sanic-org repositories'
author: 'sanic-org'
branding:
  color: 'green'
  icon: 'terminal'
inputs:
  action:
    required: false
    description: 'Kind of Operation Being Performed using the Actions. Tests/Docs/SanityCheck/Analysis'
    default: ''
  test-infra-tool:
    required: false
    description: 'Name of the Test Management Infrastructure. Defaults to Tox'
    default: 'tox'
  test-infra-version:
    required: false
    description: 'Version of the Test Management infrastructure'
    default: 'latest'
  test-additional-args:
    required: false
    description: 'Additional Arguments to be passed onto the Test Infra'
    default: ''
  test-tool-install-force:
    required: false
    description: 'Force Install the Test tool even if the Env does not need it'
    default: "false"
  linter-infra-tool:
    required: false
    description: 'Tool used to perming linting operation on the repository'
    default: 'black'
  linter-infra-version:
    required: false
    description: 'Install a specific version of linter tool chain as required'
    default: 'latest'
  linter-additional-args:
    required: false
    description: 'Additional Override argument to be passed to the Linter'
    default: ''
  python-version:
    required: true
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    default: '3.x'
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
    required: false
  token:
    description: Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
    required: false
  package-infra-name:
    required: false
    description: 'Python Package Publisher toolchain'
    default: 'twine'
  package-infra-version:
    required: false
    description: 'Version of the package publishing Infra to use'
    default: 'latest'
  pypi-user:
    required: false
    description: 'PyPi User name while publishing Package'
    default: '##DEFAULT##'
  pypi-user-password:
    required: false
    description: 'PyPi User password while publishing package'
    default: '##DEFAULT##'
  pypi-access-token:
    required: false
    description: 'PyPI Access token if you want to bypass user and password'
    default: '##DEFAULT##'
  pypi-package-dir:
    required: false
    description: 'Directory to use for creating Dist packages'
    default: 'pydist'
  pypi-verify-metadata:
    required: false
    description: 'Verify package metadata before publishing'
    default: 'true'
  pypi-skip-existing:
    required: false
    description: 'Skip If the Version of the package already exists for publishing'
    default: 'true'
  pip-version:
    required: false
    description: 'Use a specified version of Pip for Setting up the infra'
    default: 'latest'
  docker-image-suffix:
    required: false
    description: 'Unique Identifier to indicate which Dockerfile-py37 to use for build the Image'
    default: 'py37'
  tag-image-as-latest:
    required: false
    description: 'Tag Image using the base Prefix and tag as latest'
    default: 'true'
  registry-url:
    required: false
    description: 'Name of the Docker or any other registry to use for pushing docker images'
    default: 'docker.io'
  registry-auth-user:
    required: false
    description: 'Docker Registry user for publishing the Image'
    default: 'myfakeuser'
  registry-auth-password:
    required: false
    description: 'Password to authenticate against the docker registry'
    default: 'myfakepassword'
  push-images:
    required: false
    description: 'Push Generated Docker Image to upstream'
    default: 'false'
  docker-image-base-name:
    required: false
    description: 'Base Image path for pushing the docker'
    default: 'sanicframework/sanic'
  docker-build-args:
    required: false
    description: 'Build Args to use for generating Docker Images'
    default: ''
  dockerfile-base-dir:
    required: false
    description: 'In case if you have the docker file defined in sub path, you can specify that directory'
    default: '.'
  image-infra-tool:
    required: false
    description: 'Tool chain to use for building docker images'
    default: 'docker'
  ignore-python-setup:
    required: false
    description: 'Ignore Setting up Python infra if you are running just docker builds'
    default: 'false'
  spellcheck-infra-name:
    required: false
    description: 'Name of the Spell Check Infra used. (Currently supported tools are only python based)'
    default: 'pyspelling'
  spellcheck-infra-version:
    required: false
    description: 'Version of the spell check infra to install'
    default: 'latest'
  spellcheck-additional-args:
    required: false
    description: 'Additional Argument to be passed for performing Spell check'
    default: ''
  spellcheck-ignore-errors:
    required: false
    description: 'Ignore Spell Check errors and do not fail the task'
    default: 'false'
  spellcheck-force:
    required: false
    description: 'Force Spell check to Run Always if the action is set to spellcheck'
    default: 'true'
  comment-rebase-pattern:
    required: false
    description: 'Rebase Comment Pattern Indicator'
    default: '.*\@bot\s+\/rebase.*'
  git-access-token:
    required: false
    description: 'GitHub Access Token for interacting with Git Infra'
    default: ''
  experimental-ignore-error:
    required: false
    description: 'Enable Experimental Python Workflow where errors can be ignored'
    default: 'false'
outputs:
  python-version:
    description: "The installed python version. Useful when given a version range as input."
  test-infra-version:
    description: 'Currently installed version of the Test Infra Package'
  linter-infra-version:
    description: 'Version of the Linter tool configured'
  pip-version:
    description: 'Version of the Pip Package Installed'
  package-infra-version:
    description: 'Package Deployment Infra Version'
  image-infra-version:
    description: 'Version of the Infra used to build the docker images'
  image-infra-generated-list:
    description: 'List of Docker images in the infra after the generation was done'
  spellcheck-infra-version:
    description: 'Version of the Spell Check Infra used'
runs:
  using: 'node12'
  main: 'dist/index.js'
